[WIP] first logging draft
roadrunner-craft/core pull request #23
Opened 2020-05-27 03:39 UTC by filedesless

2020-06-06 00:42 UTC, filedesless commented
TODO: add terminal coloring and cap logfile size.

2020-06-07 18:21 UTC, afrigon requested changes

2020-06-07 18:21 UTC, afrigon commented on src/utils/time.rs
> +        .unwrap()
👁👄👁

2020-06-07 18:21 UTC, afrigon commented on src/utils/time.rs
> +        "{:02}h {:02}m {:02}s {:03}ms",
I think a format like this would be better `hh:mm:ss +0000`

2020-06-07 18:21 UTC, afrigon commented on src/utils/time.rs
> +pub fn ms_since_epoch() -> u128 {
you should make this return a duration to make it usable in more places

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/mod.rs
> +    log::set_boxed_logger(Box::new(multi_logger::MultiLogger { loggers: loggers })).unwrap();
if the params as the same name as the value, it can be simplified, ex: `{ loggers: loggers }` becomes `{ loggers }`

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_file.rs
> +const CURRENT_LOG: &str = "current.log";
how about prefixing all the log files with the crate name ?

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_file.rs
> +const LOG_DIR: &str = "logs/";
the log dir could probably be passed in the constructor ? would make it more flexible

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_file.rs
> +const LOG_DIR: &str = "logs/";
Maybe it could take in a FileLoggerOption as a parameter and have all of these options

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_file.rs
> +pub struct LogFile {
this should be called FileLogger

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_stdout.rs
> +pub struct LogStdOut {
this should be called `StdoutLogger`

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_stdout.rs
> +            "[{}] - ({}): {}\n",
could be nice to have the format passed with the options eventually with constants

something like the python logging module does.

`formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')`

2020-06-07 18:21 UTC, afrigon commented on src/utils/logging/log_file.rs
> +const CURRENT_LOG: &str = "current.log";
maybe roadrunner.log.timestamp to make life easier when rotating

2020-06-07 18:21 UTC, afrigon commented on src/lib.rs
> +extern crate lazy_static;
maybe re-export lazy-static for the client and servers to use? would be nice to have it under `core::utils::lazy_static`

2020-06-07 18:21 UTC, afrigon commented on src/utils/time.rs
> +    time_since(PROGRAM_START.elapsed())
I feel like this utils function is a bit useless, doesn't do much

2020-06-07 18:21 UTC, afrigon commented on Cargo.toml
> +colored = "1.9"
we should use `https://docs.rs/termcolor/1.1.0/termcolor/enum.Color.html` to get the rgb colors instead of being limited to the basic colors

2020-06-07 19:33 UTC, afrigon commented on src/utils/logging/log_stdout.rs
> +            "[{}] - ({}): {}\n",
maybe overkill

2020-06-07 19:52 UTC, afrigon commented on src/utils/logging/log_stdout.rs
> +    stdout: Mutex<Stdout>,
would this remove the need for the mutex ? `https://doc.rust-lang.org/std/io/struct.StdoutLock.html`

2020-06-08 01:04 UTC, merged